// Pricing page and limit-dialog text. Learner UI is uz/ru/en.
export const COPY = {
  uz: {
    title: 'Narxlar',
    sub: "O'quvchi uchun asosiy narsa bepul. O'quv markazlar kichikdan boshlab, o'sgan sari to'laydi.",
    forLearners: "O'quvchi uchun",
    forCenters: "O'quv markazlar uchun",
    month: 'oyiga',
    year: 'yiliga',
    free: 'Bepul',
    custom: 'Kelishuv asosida',
    names: { free: 'Bepul', plus: 'Plus', start: 'Start', standard: 'Standard', pro: 'Pro', custom: 'Maxsus' },
    packs: (n) => (n === Infinity ? 'Cheksiz pack' : `${n} tagacha o'z pack'ingiz`),
    students: (n) => (n === Infinity ? "Cheksiz o'quvchi" : `${n} tagacha o'quvchi`),
    groups: (n) => (n === Infinity ? 'Cheksiz guruh' : `${n} ta guruh`),
    everything: "Barcha o'rganish usullari, eslatmalar va statistika",
    centerAll: "Guruhlar, uy vazifasi, ustoz va admin paneli",
    perStudent: "bir o'quvchiga oyiga ~",
    cta: "Markaz ochish",
    ctaLearner: 'Boshlash',
    note: "To'lov hozircha qo'lda qabul qilinadi: Telegramda yozing. Rejangiz tugasa, 14 kun qo'shimcha muddat beriladi va ma'lumotlaringiz hech qachon o'chmaydi.",
    launch: "Hozircha hamma o'quvchilar uchun Plus bepul.",
    popular: "Eng ko'p tanlanadi",
    limitTitle: "Pack limitiga yetdingiz",
    limitBody: (n) => `Bepul rejada ${n} tagacha o'z pack'ingizni yaratish mumkin. Eskilarini o'chirmasdan ham tayyor pack'lardan foydalanishda davom etishingiz mumkin.`,
    seePlans: 'Narxlarni ko\'rish',
    close: 'Yopish',
  },
  ru: {
    title: 'Цены',
    sub: 'Для учеников основное бесплатно. Учебные центры начинают с малого и платят по мере роста.',
    forLearners: 'Для учеников',
    forCenters: 'Для учебных центров',
    month: 'в месяц',
    year: 'в год',
    free: 'Бесплатно',
    custom: 'По договорённости',
    names: { free: 'Бесплатно', plus: 'Plus', start: 'Start', standard: 'Standard', pro: 'Pro', custom: 'Особый' },
    packs: (n) => (n === Infinity ? 'Безлимит паков' : `до ${n} своих паков`),
    students: (n) => (n === Infinity ? 'Безлимит учеников' : `до ${n} учеников`),
    groups: (n) => (n === Infinity ? 'Безлимит групп' : `${n} гр.`),
    everything: 'Все способы обучения, напоминания и статистика',
    centerAll: 'Группы, домашние задания, панели учителя и админа',
    perStudent: 'на ученика в месяц ~',
    cta: 'Открыть центр',
    ctaLearner: 'Начать',
    note: 'Оплата пока принимается вручную: напишите нам в Telegram. После окончания плана даётся 14 дней, данные никогда не удаляются.',
    launch: 'Сейчас Plus бесплатен для всех учеников.',
    popular: 'Выбирают чаще всего',
    limitTitle: 'Достигнут лимит паков',
    limitBody: (n) => `В бесплатном плане можно создать до ${n} своих паков. Готовыми паками можно пользоваться и дальше, ничего удалять не нужно.`,
    seePlans: 'Смотреть цены',
    close: 'Закрыть',
  },
  en: {
    title: 'Pricing',
    sub: 'Free for learners. Learning centers start small and pay as they grow.',
    forLearners: 'For learners',
    forCenters: 'For learning centers',
    month: 'per month',
    year: 'per year',
    free: 'Free',
    custom: 'Custom',
    names: { free: 'Free', plus: 'Plus', start: 'Start', standard: 'Standard', pro: 'Pro', custom: 'Custom' },
    packs: (n) => (n === Infinity ? 'Unlimited packs' : `Up to ${n} packs of your own`),
    students: (n) => (n === Infinity ? 'Unlimited students' : `Up to ${n} students`),
    groups: (n) => (n === Infinity ? 'Unlimited groups' : `${n} group${n === 1 ? '' : 's'}`),
    everything: 'Every study mode, reminders and statistics',
    centerAll: 'Groups, homework, teacher and admin panels',
    perStudent: 'per student per month ~',
    cta: 'Start a center',
    ctaLearner: 'Get started',
    note: 'Payment is handled manually for now: message us on Telegram. When a plan ends you get 14 extra days and your data is never deleted.',
    launch: 'For now, Plus is free for every learner.',
    popular: 'Most popular',
    limitTitle: 'Pack limit reached',
    limitBody: (n) => `The free plan lets you create up to ${n} packs of your own. You can keep using ready-made packs; nothing is deleted.`,
    seePlans: 'See plans',
    close: 'Close',
  },
};
