// Generated by eval/fit.js — do not edit by hand. Regenerate with: npm run fit:memory
export const DEFAULT_PREDICTOR_PARAMS = {
  "bias": 2.57352,
  "weights": [
    0.1084,
    0.651,
    -0.1515,
    0.3978,
    -0.2787,
    0.2346
  ],
  "mu": [
    2.1116,
    2.2509,
    1.024,
    2.1313,
    0.235,
    3.9272
  ],
  "sd": [
    0.5022,
    1.4183,
    1.5495,
    0.8008,
    0.424,
    1.3771
  ],
  "meta": {
    "fittedAt": "2026-10-05",
    "predictions": 37852,
    "users": 24,
    "heldOut": {
      "n": 10837,
      "brier": 0.06808458091761577,
      "logLoss": 0.24422784717991816,
      "auc": 0.7805597980025762,
      "ece": 0.015611801789847637
    },
    "featureNames": [
      "userRate",
      "wordRate",
      "logGapH",
      "logIdx",
      "active",
      "prevConf"
    ]
  }
};
