// Copy for the sign-in / sign-up pages, Uzbek (default) and English.

export const AUTH_CONTENT = {
  uz: {
    langLabel: 'Til',
    back: 'Bosh sahifa',
    show: "Parolni ko'rsatish",
    hide: 'Parolni yashirish',
    or: 'yoki',
    google: 'Google bilan davom etish',
    aside: {
      title: 'Bugungi takrorlash',
      sample: "Namuna ma'lumot",
      status: { good: 'YAXSHI', soon: 'TEZDA', due: 'TAKRORLANG' },
      line: "Har bir so'zning o'z vaqti bor.",
    },
    login: {
      title: 'Xush kelibsiz',
      sub: 'Email yoki telefon raqamingiz bilan kiring.',
      identifier: 'Email yoki telefon raqami',
      password: 'Parol',
      forgot: 'Parolni unutdingizmi?',
      submit: 'Kirish',
      noAccount: "Hisobingiz yo'qmi?",
      signUp: "Ro'yxatdan o'tish",
      reset: {
        title: 'Parolni tiklash',
        sub: 'Emailingizni kiriting, tiklash havolasini yuboramiz.',
        email: 'Email',
        submit: 'Havolani yuborish',
        back: 'Kirishga qaytish',
        sent: "Agar bu email bilan hisob mavjud bo'lsa, parolni tiklash havolasi yuborildi. Pochtangizni (spam papkasini ham) tekshiring.",
      },
      errors: {
        fill: "Barcha maydonlarni to'ldiring.",
        enterEmail: 'Email manzilingizni kiriting.',
      },
    },
    register: {
      title: 'Hisob yarating',
      sub: 'Ismingiz, email va parol yetarli.',
      name: 'Ism',
      email: 'Email',
      password: 'Parol',
      confirm: 'Parolni tasdiqlang',
      submit: "Ro'yxatdan o'tish",
      haveAccount: 'Hisobingiz bormi?',
      signIn: 'Kirish',
      strength: { weak: 'Zaif', medium: "O'rtacha", strong: 'Kuchli' },
      errors: {
        name: 'Ismingizni kiriting.',
        email: 'Email manzilingizni kiriting.',
        emailBad: "Email manzili noto'g'ri (masalan name@domain.com).",
        short: "Parol kamida 6 belgidan iborat bo'lishi kerak.",
        mismatch: 'Parollar mos kelmadi.',
      },
    },
    firebase: {
      'auth/invalid-email': "Email manzili noto'g'ri.",
      'auth/user-disabled': "Bu hisob o'chirilgan.",
      'auth/user-not-found': 'Bunday hisob topilmadi.',
      'auth/wrong-password': "Parol noto'g'ri.",
      'auth/invalid-credential': "Email yoki parol noto'g'ri.",
      'auth/too-many-requests': "Urinishlar ko'p. Keyinroq qayta urinib ko'ring.",
      'auth/network-request-failed': 'Tarmoq xatosi. Internetni tekshiring.',
      'auth/popup-closed-by-user': 'Kirish oynasi yopildi.',
      'auth/email-already-in-use': "Bu email allaqachon ro'yxatdan o'tgan.",
      'auth/weak-password': 'Parol juda oddiy. Kamida 6 belgi ishlating.',
      fallback: "Xatolik yuz berdi. Qayta urinib ko'ring.",
    },
  },
  en: {
    langLabel: 'Language',
    back: 'Home',
    show: 'Show password',
    hide: 'Hide password',
    or: 'or',
    google: 'Continue with Google',
    aside: {
      title: "Today's review",
      sample: 'Sample data',
      status: { good: 'GOOD', soon: 'SOON', due: 'REVIEW' },
      line: 'Every word has its own time.',
    },
    login: {
      title: 'Welcome back',
      sub: 'Sign in with your email or phone number.',
      identifier: 'Email or phone number',
      password: 'Password',
      forgot: 'Forgot password?',
      submit: 'Sign in',
      noAccount: "Don't have an account?",
      signUp: 'Sign up',
      reset: {
        title: 'Reset password',
        sub: "Enter your email and we'll send a reset link.",
        email: 'Email',
        submit: 'Send reset link',
        back: 'Back to sign in',
        sent: 'If an account exists for this email, a password reset link has been sent. Check your inbox (including spam).',
      },
      errors: {
        fill: 'Please fill in all fields.',
        enterEmail: 'Please enter your email address.',
      },
    },
    register: {
      title: 'Create your account',
      sub: 'Your name, email and a password is all it takes.',
      name: 'Name',
      email: 'Email',
      password: 'Password',
      confirm: 'Confirm password',
      submit: 'Sign up',
      haveAccount: 'Already have an account?',
      signIn: 'Sign in',
      strength: { weak: 'Weak', medium: 'Medium', strong: 'Strong' },
      errors: {
        name: 'Please enter your name.',
        email: 'Please enter your email address.',
        emailBad: 'Invalid email address (e.g. name@domain.com).',
        short: 'Password must be at least 6 characters.',
        mismatch: 'Passwords do not match.',
      },
    },
    firebase: {
      'auth/invalid-email': 'Invalid email address.',
      'auth/user-disabled': 'This account has been disabled.',
      'auth/user-not-found': 'No account found with these details.',
      'auth/wrong-password': 'Incorrect password.',
      'auth/invalid-credential': 'Incorrect email or password.',
      'auth/too-many-requests': 'Too many attempts. Please try again later.',
      'auth/network-request-failed': 'Network error. Check your connection.',
      'auth/popup-closed-by-user': 'Sign-in window was closed.',
      'auth/email-already-in-use': 'This email is already registered.',
      'auth/weak-password': 'Password is too weak. Use at least 6 characters.',
      fallback: 'Something went wrong. Please try again.',
    },
  },
};

export function firebaseMessage(copy, code) {
  return copy.firebase[code] || copy.firebase.fallback;
}
